-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 18:37:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_software_precisao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_software_precisao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_software_precisao` DEFAULT CHARACTER SET utf8 ;
USE `db_software_precisao` ;

-- -----------------------------------------------------
-- Table `db_software_precisao`.`tb001_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_software_precisao`.`tb001_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(255) NULL,
  `email_user` VARCHAR(180) NULL,
  `senha_user` VARCHAR(100) NULL,
  `telefone_user` VARCHAR(45) NULL,
  `datacreate_user` DATETIME NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_software_precisao`.`tb002_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_software_precisao`.`tb002_plano` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(100) NULL,
  `descricao_plano` VARCHAR(255) NULL,
  `valor_plano` DECIMAL(10,2) NULL,
  `tb001_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_plano`),
  INDEX `fk_tb002_plano_tb001_user_idx` (`tb001_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_tb002_plano_tb001_user`
    FOREIGN KEY (`tb001_user_id_user`)
    REFERENCES `db_software_precisao`.`tb001_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
